volumes:
  mongodb_data:

services:
  db:
    build: ./mdb
    image: arch_practice_4_db_image
    container_name: arch_practice_4_db_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
